apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth
  namespace: local-setup
spec:
  replicas: 1
  serviceName: geth
  volumeClaimTemplates:
    - metadata:
        name: geth-data
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: ropsten-miner # use SSD storage
        resources:
          requests:
            storage: 1Gi
  selector:
    matchLabels:
      app: geth
      type: local
  template:
    metadata:
      labels:
        app: geth
        type: local
    spec:
      volumes:
        - name: geth-data
          persistentVolumeClaim:
            claimName: geth-data
        - name: accounts-private-keys
          configMap:
            name: accounts-private-keys
        - name: geth-genesis
          configMap:
            name: geth-config
            items:
              - key: genesis.json
                path: genesis.json
        - name: geth-password
          configMap:
            name: geth-config
            items:
              - key: password.txt
                path: password.txt
      containers:
        - name: geth
          image: ethereum/client-go:v1.9.9
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 30303
          volumeMounts:
            - name: geth-data
              mountPath: /root/.ethereum
            - name: accounts-private-keys
              mountPath: /root/private-keys
            - name: geth-genesis
              mountPath: /root/genesis/genesis.json
              subPath: genesis.json
            - name: geth-password
              mountPath: /root/password/password.txt
              subPath: password.txt
          env:
            - name: ETHERBASE
              valueFrom:
                configMapKeyRef:
                  name: geth-config
                  key: etherbase
          command: [ "sh" ]
          args:
            - "-c"
            - "geth init /root/genesis/genesis.json && \
               for filename in /root/private-keys/*.txt; do geth account import --password /root/password/password.txt $filename; done && \
               geth --networkid 1101 --identity \"somerandomidentity\" \
               --ws --wsaddr \"0.0.0.0\" --wsport \"8546\" --wsorigins \"*\" \
               --rpc --rpcport \"8545\" --rpcaddr \"0.0.0.0\" --rpccorsdomain \"*\" \
               --rpcapi \"db,ssh,miner,admin,eth,net,web3,personal,debug\" \
               --wsapi \"db,ssh,miner,admin,eth,net,web3,personal\" \
               --syncmode \"fast\" \
               --mine --miner.threads=1 --miner.etherbase=$ETHERBASE \
               --unlock $ETHERBASE --password /root/password/password.txt \
               --allow-insecure-unlock"

