[ethereum]
  URL = "ws://127.0.0.1:8546"

[ethereum.account]
  KeyFile = "WORKDIR/ethereum/data/keystore/UTC--2019-08-01T13-19-44.188278000Z--b7021acafecf289fa345ecc95ecab18077530841"

[ethereum.ContractAddresses]
  BondedECDSAKeepFactory = "0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  TBTCSystem = "0xBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"


[Storage]
  DataDir = "WORKDIR/storage/keep-ecdsa/2"

[LibP2P]
  Port = 3921
  Peers = ["/ip4/127.0.0.1/tcp/3920/ipfs/16Uiu2HAmL3fUCp1BCpewHzxcnUf3R1ZoL82CSVVNE6zvi9zUcP1T"]
